title: Blog Bibliotheks- und Archivinformatik
author: Lua
email: jessica.weidmann@stud.fhgr.ch
description: > # this means to ignore newlines
  Lerntagebuch im Kurs Bibliotheks- und Archivinformatik

# social links
twitter_username: felixlohmeier # DO NOT include the @ character, or else the build will fail!
github_username:  luaynara # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
